### ISSUE TITLE
Uncaught TypeError: React.createClass is not a function

### ISSUE THREAD

**Issue by VishalSwarnkar** [hggeorgiev/react-rails-tutorial#1]
jsx React.DOM is not working when tried loading the http://localhost:3000/
Could you please help me in resolving this problem?

**Comment by chrislotix** [comment]
I stumbled upon the same problem. It might have something to do with the fact that react replaced 'createClass' with 'createReactClass' with version 16 (which was released after the guide was finished) Not entirely sure though. Can you show the code that throws this error?

**Comment by swarnv01** [comment]
With gem 'react-rails', '~> 2.4.4' and gem 'rails', '~> 5.1.5' throw an error: Undefined function createClass 

But when used gem 'rails', '~> 5.1.0' and gem 'react-rails', '~> 2.2.0' it worked like charm.

However I endup in another issue here when using references.
`Uncaught TypeError: Cannot read property 'value' of undefined`

https://github.com/Kaizeras/react-rails-tutorial/blob/master/app/assets/javascripts/components/_new_item.js.jsx#L17 in place of that I have to use "<input id='name' placeholder='Enter the name of the item'></input>" to resolve it.

**Comment by VishalSwarnkar** [comment]
With gem 'react-rails', '~> 2.4.4' and gem 'rails', '~> 5.1.5' throw an error: Undefined function createClass 

But when used gem 'rails', '~> 5.1.0' and gem 'react-rails', '~> 2.2.0' it worked like charm.

However, I end up in another issue here when using references.
`Uncaught TypeError: Cannot read property 'value' of undefined`

https://github.com/Kaizeras/react-rails-tutorial/blob/master/app/assets/javascripts/components/_new_item.js.jsx#L17 in place of that I have to use "<input id='name' placeholder='Enter the name of the item'></input>" to resolve it.

**Comment by chrislotix** [comment]
Downgrading makes sense  https://github.com/reactjs/react-rails/blob/master/CHANGELOG.md 
Version >=2.1.0 support rails 5.1 and react  < 16. Introduction of 2.3.1 version might be where the problems could start arising.

I will hack around tomorrow and post results. Thank you for good lead @VishalSwarnkar

**Comment by chrislotix** [comment]
downgrading `gem 'react-rails', "2.3.1"` fixes the issue for me, would be cool if it was made clear for which version the tutorial is made.
